Add checksum checks

diff --git a/usr/share/device-quirks/scripts/override_dsdt b/usr/share/device-quirks/scripts/override_dsdt
--- a/usr/share/device-quirks/scripts/override_dsdt
+++ b/usr/share/device-quirks/scripts/override_dsdt
@@ -18,22 +18,50 @@ DEPLOYMENT_DSDT_PATH="${SUBVOL}/usr/lib/firmware/dsdt/${1}"
 BOOTLOADER_CONFIG="${MOUNT_PATH}/boot/loader/entries/frzr.conf"
 ACPI_OVERRIDE_DEVICE="${split_arr[0]}_acpi_override"
 
-if ! grep -q "${ACPI_OVERRIDE_DEVICE}" ${BOOTLOADER_CONFIG}; then
+# Before doing anything we must check the checksum of the device in use against the known pool of patchable firmwares
+cat /sys/firmware/acpi/tables/DSDT > system-dumped-dsdt.dat
+# Dump DSDT from the system
+iasl -d system-dumped-dsdt.dat
+iasl -tc system-dumped-dsdt.dat
 
-  if [ ! -d "${ACPI_BUILD_DIR}" ]; then
-    # create directory for acpi DSDT overrides
-    mkdir -p "${ACPI_BUILD_DIR}"
-  fi
+dsl_file="system-dumped-dsdt.dsl"
 
-  cp ${DEPLOYMENT_DSDT_PATH} ${ACPI_BUILD_DIR}/dsdt.dsl
-  echo "Compiling DSDT..."
-  iasl -tc ${ACPI_BUILD_DIR}/dsdt.dsl
-  cd /tmp/
-  find kernel | cpio -H newc --create > ${ACPI_OVERRIDE_DEVICE}
-  cp ${ACPI_OVERRIDE_DEVICE} ${MOUNT_PATH}/boot
-  echo "Adding $ACPI_OVERRIDE_DEVICE to bootloader"
-  sed -i "s|linux .*/vmlinuz-linux|&\ninitrd /${ACPI_OVERRIDE_DEVICE}|" ${BOOTLOADER_CONFIG}
-  echo "Done!"
+# Use sed to extract the checksum value from the DSL file
+checksum=$(sed -n 's/.*Checksum[[:space:]]\+\(0x[[:xdigit:]]\+\).*/\1/p' "$dsl_file")
+checksum2=$(sed -n 's/.*Checksum[[:space:]]\+\(0x[[:xdigit:]]\+\).*/\1/p' "${SUBVOL}/usr/lib/firmware/dsdt/${1}")
+apply_patch=0
+
+echo "Checksum value from system dump: $checksum"
+echo "Checksum of shipped DSDT: $checksum2"
+
+# Compare the checksums
+if [ "$checksum" = "$checksum2" ]; then
+  echo "Checksums match! We are able to patch the firmware"
+  apply_patch=1
 else
-  echo "$ACPI_OVERRIDE_DEVICE already detected in bootloader, exiting"
+  echo "Checksums do not match! We can't apply the patch!"
 fi
+
+if [[ ${apply_patch} -eq 1 ]]; then
+  if ! grep -q "${ACPI_OVERRIDE_DEVICE}" ${BOOTLOADER_CONFIG}; then
+    if [ ! -d "${ACPI_BUILD_DIR}" ]; then
+      # create directory for acpi DSDT overrides
+      mkdir -p "${ACPI_BUILD_DIR}"
+    fi
+
+    cp ${DEPLOYMENT_DSDT_PATH} ${ACPI_BUILD_DIR}/dsdt.dsl
+    echo "Compiling DSDT..."
+    iasl -tc ${ACPI_BUILD_DIR}/dsdt.dsl
+    cd /tmp/
+    find kernel | cpio -H newc --create > ${ACPI_OVERRIDE_DEVICE}
+    cp ${ACPI_OVERRIDE_DEVICE} ${MOUNT_PATH}/boot
+    echo "Adding $ACPI_OVERRIDE_DEVICE to bootloader"
+    sed -i "s|linux .*/vmlinuz-linux|&\ninitrd /${ACPI_OVERRIDE_DEVICE}|" ${BOOTLOADER_CONFIG}
+    echo "Done!"
+  else
+    echo "$ACPI_OVERRIDE_DEVICE already detected in bootloader, exiting"
+  fi
+else
+  echo "Cannot apply the patch. Checksums do not match!"
+fi
+
