Add exit codes to id-script and draft the air plus script

diff --git a/usr/share/device-quirks/id-device b/usr/share/device-quirks/id-device
--- a/usr/share/device-quirks/id-device
+++ b/usr/share/device-quirks/id-device
@@ -1,6 +1,7 @@
 #/bin/bash
 ### SYSTEM IDENTIFICATION SCRIPT
-
+### This script has support for the frzr-deployment system that will Use exit codes to tell frzr-initramfs if the initramfs needs rebuilt
+### exit 0 to call frzr-initramfs, exit 7 to not call.
 export DQ_PATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 VENDOR="$(cat /sys/devices/virtual/dmi/id/board_vendor)"
 ### DEVICE LISTS
@@ -12,21 +13,26 @@ OXP_LIST="ONE-NETBOOK TECHNOLOGY CO., LTD."
 
 # AOKZOE Devices
 if [[ ":$AOK_LIST:" =~ "${VENDOR}" ]]; then
-    $DQ_PATH/scripts/aokzoe/aokzoe_table.sh
+    #$DQ_PATH/scripts/aokzoe/aokzoe_table.sh
+    exit 0
 
 # Aya Neo Devices
 elif [[ ":$AYANEO_LIST:" =~ "${VENDOR}" ]]; then
-    $DQ_PATH/scripts/ayaneo/ayaneo_table.sh
+    #$DQ_PATH/scripts/ayaneo/ayaneo_table.sh
+    exit 7
 
 # GPD Devices
 elif [[ ":$GPD_LIST:" =~ "${VENDOR}" ]]; then
-    $DQ_PATH/scripts/gpd/gpd_table.sh
+    #$DQ_PATH/scripts/gpd/gpd_table.sh
+    exit 7
 
 # OXP Devices
 elif [[ ":$OXP_LIST:" =~ "${VENDOR}" ]]; then
-    $DQPATH/scripts/oxp/oxp_table.sh
+    #$DQPATH/scripts/oxp/oxp_table.sh
+    exit 0
 
 # Unrecognized Device
 else
-    echo "${VENDOR} does not have any supported models. Exiting."
+    #echo "${VENDOR} does not have any supported models. Exiting."
+    exit 7
 fi
